//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFrameForProjectModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcFrameForPorjectSqlModelContainer : DbContext
    {
        public MvcFrameForPorjectSqlModelContainer()
            : base("name=MvcFrameForPorjectSqlModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UsersDb> UsersDbSet { get; set; }
        public virtual DbSet<UserClassDb> UserClassDbSet { get; set; }
        public virtual DbSet<ResourceDb> ResourceDbSet { get; set; }
        public virtual DbSet<InformationDb> InformationDbSet { get; set; }
        public virtual DbSet<CommentDb> CommentDbSet { get; set; }
        public virtual DbSet<InformationTypeDb> InformationTypeDbSet { get; set; }
        public virtual DbSet<ResourceTypeDb> ResourceTypeDbSet { get; set; }
        public virtual DbSet<ConfigDb> ConfigDbSet { get; set; }
    }
}
